/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SimpleScene: typeof import('./src/components/SimpleScene.vue')['default']
    TestScene: typeof import('./src/components/TestScene.vue')['default']
    TresAmbientLight: typeof import('@tresjs/core')['TresAmbientLight']
    TresBoxGeometry: typeof import('@tresjs/core')['TresBoxGeometry']
    TresCanvas: typeof import('@tresjs/core')['TresCanvas']
    TresDirectionalLight: typeof import('@tresjs/core')['TresDirectionalLight']
    TresMesh: typeof import('@tresjs/core')['TresMesh']
    TresMeshStandardMaterial: typeof import('@tresjs/core')['TresMeshStandardMaterial']
    TresPerspectiveCamera: typeof import('@tresjs/core')['TresPerspectiveCamera']
  }
}
